version: "3"

networks:
    default:

services:
    lavalink:
        image: fredboat/lavalink:master
        container_name: lavalink
        volumes:
            - ./lavalink/application.yaml:/opt/Lavalink/application.yaml
        networks:
            - default

    bot:
        image: reynadi17/musicbot
        container_name: bot
        env_file:
            - .env
        networks:
            - default
        depends_on:
            - lavalink
        links:
            - lavalink
